# Generated by Django 3.1.7 on 2021-03-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=120, unique=True)),
                ('book_price', models.IntegerField()),
                ('book_pages', models.IntegerField()),
                ('book_author', models.CharField(max_length=120)),
            ],
        ),
    ]
